"""remove meterVersion to table Flowdirect

Revision ID: 22f0cf363cf7
Revises: e7e9345f8bf1
Create Date: 2025-10-05 09:07:08.138990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f0cf363cf7'
down_revision: Union[str, Sequence[str], None] = 'e7e9345f8bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_direct', sa.Column('meterVersion', sa.Integer(), nullable=True))
    op.drop_column('psi', 'meterVersion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psi', sa.Column('meterVersion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('flow_direct', 'meterVersion')
    # ### end Alembic commands ###
