"""added table with individual settings for diller

Revision ID: 6858726bb8b3
Revises: 83fc3a125be0
Create Date: 2025-11-06 12:22:47.751220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6858726bb8b3'
down_revision: Union[str, Sequence[str], None] = '83fc3a125be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributer_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apn', sa.String(length=50), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('neo_server_adress', sa.String(length=100), nullable=True),
    sa.Column('mqtt_server_adress', sa.String(length=50), nullable=True),
    sa.Column('minimal_signal_level', sa.String(length=10), nullable=True),
    sa.Column('minimal_temp_for_gps', sa.String(length=10), nullable=True),
    sa.Column('allways_on_display', sa.String(length=10), nullable=True),
    sa.Column('menu_auto_rotation', sa.String(length=10), nullable=True),
    sa.Column('work_flow_indication', sa.String(length=10), nullable=True),
    sa.Column('atm_pressure', sa.String(length=10), nullable=True),
    sa.Column('standard_pressure', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('distributer', sa.Column('distributer_settings_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'distributer', ['distributer_settings_id'])
    op.create_foreign_key(None, 'distributer', 'distributer_settings', ['distributer_settings_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'distributer', type_='foreignkey')
    op.drop_constraint(None, 'distributer', type_='unique')
    op.drop_column('distributer', 'distributer_settings_id')
    op.drop_table('distributer_settings')
    # ### end Alembic commands ###
