"""add information in table psi verification date

Revision ID: 6a63035bcf34
Revises: ed75746ffd6c
Create Date: 2025-09-05 12:27:50.633432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a63035bcf34'
down_revision: Union[str, Sequence[str], None] = 'ed75746ffd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psi', sa.Column('verification_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psi', 'verification_date')
    # ### end Alembic commands ###
