"""table passport_version added, table psi added actual verification date and number of verifications

Revision ID: 83fc3a125be0
Revises: fc47fe3b3fc2
Create Date: 2025-11-02 12:25:01.484065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fc3a125be0'
down_revision: Union[str, Sequence[str], None] = 'fc47fe3b3fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passport_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('actual_temlate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('psi', sa.Column('verification_date_actual', sa.Date(), nullable=True))
    op.add_column('psi', sa.Column('number_of_verifications', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psi', 'number_of_verifications')
    op.drop_column('psi', 'verification_date_actual')
    op.drop_table('passport_version')
    # ### end Alembic commands ###
