"""First migration

Revision ID: ba1225c3825d
Revises: 
Create Date: 2025-08-03 17:40:34.658855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1225c3825d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psi', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('psi', 'imei',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('psi', 'meterNum',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('psi', 'meterSize',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('psi', 'psiPerson',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('psi', 'psiDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('regions', 'region_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'region_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('psi', 'psiDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('psi', 'psiPerson',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('psi', 'meterSize',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('psi', 'meterNum',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('psi', 'imei',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('psi', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
