"""add meter version to table psi and pasport

Revision ID: e7e9345f8bf1
Revises: 3a055bfb1752
Create Date: 2025-10-04 13:04:24.490077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e9345f8bf1'
down_revision: Union[str, Sequence[str], None] = '3a055bfb1752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psi', sa.Column('meterVersion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psi', 'meterVersion')
    # ### end Alembic commands ###
