"""empty message

Revision ID: ed75746ffd6c
Revises: ba1225c3825d
Create Date: 2025-08-04 17:40:35.595790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed75746ffd6c'
down_revision: Union[str, Sequence[str], None] = 'ba1225c3825d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psi', sa.Column('verification_done', sa.Boolean(), nullable=True))
    op.alter_column('psi', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('psi', 'imei',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('psi', 'meterNum',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('psi', 'meterSize',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('psi', 'plombNum',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('psi', 'plombNum',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('psi', 'meterSize',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('psi', 'meterNum',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('psi', 'imei',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('psi', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('psi', 'verification_done')
    # ### end Alembic commands ###
