"""table psi added valveType

Revision ID: fc47fe3b3fc2
Revises: 22f0cf363cf7
Create Date: 2025-11-01 15:40:47.824094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc47fe3b3fc2'
down_revision: Union[str, Sequence[str], None] = '22f0cf363cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psi', sa.Column('valveType', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psi', 'valveType')
    # ### end Alembic commands ###
